'use strict';
const $ = id => document.getElementById(id);
function randomID(){const b=new Uint8Array(16);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('');}
let token='',client='',revision='',semanticRevision='',busy=false,timer=null,lastStatus={},stats={rx:0,tx:0,frames:0,actions:0,errors:[]};
try{token=sessionStorage.getItem('wc-token')||'';client=sessionStorage.getItem('wc-client')||randomID();sessionStorage.setItem('wc-client',client);}catch{client=randomID();}
const fragment=new URLSearchParams(location.hash.slice(1));
if(fragment.has('token')){token=fragment.get('token');history.replaceState(null,'',location.pathname);try{sessionStorage.setItem('wc-token',token);}catch{}}
function note(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);}
function bytes(n){return n<1024?`${n} B`:`${(n/1024).toFixed(2)} KiB`;}
async function api(path,data={}){
 const body=JSON.stringify(data);stats.tx+=new TextEncoder().encode(body).length;
 const abort=new AbortController(),timeout=setTimeout(()=>abort.abort(),18000);
 try{const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token,'X-WC-Client':client},body,signal:abort.signal,credentials:'omit',cache:'no-store'});const raw=await r.arrayBuffer();stats.rx+=raw.byteLength;
 if(!r.ok){const e=JSON.parse(new TextDecoder().decode(raw));throw Object.assign(new Error(e.message),{code:e.error});}
 return r.headers.get('content-type').includes('tiles')?raw:JSON.parse(new TextDecoder().decode(raw));
 }catch(e){if(e.name==='AbortError')throw Object.assign(new Error('请求超时，操作结果可能未知；先核对原窗口，不自动重试。'),{code:'timeout'});throw e;}finally{clearTimeout(timeout);}
}
async function run(fn){if(busy)return;busy=true;$('window').disabled=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){note(e.message,true);stats.errors.push({time:new Date().toISOString(),code:e.code||e.name});stats.errors=stats.errors.slice(-30);stopAuto();if(e.code==='auth'||e.code==='expired'){$('pair').hidden=false;$('linkState').textContent='需重新连接';}}finally{busy=false;$('window').disabled=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function resetView(){revision='';semanticRevision='';$('canvas').style.display='none';$('empty').hidden=false;$('nodes').replaceChildren();$('clickMode').checked=false;stopAuto();}
async function status(){lastStatus=await api('status');const s=lastStatus;const p=s.permissions;$('permissions').textContent=`辅助功能：${p.accessibility?'已授权':'未授权'} · 屏幕录制：${p.screen_recording?'已授权':'未授权'}${p.fixture?' · ⚠ 合成测试环境，不是真实 Mac':''}`;$('target').textContent=s.window?`${s.window.app} / ${s.window.title||'无标题'} · 窗口 ${s.window.id}`:'尚未选择';$('linkState').textContent=s.control?'已连接 · 有控制权':'已连接 · 只读';$('budget').textContent=`画面预算：${bytes(s.budget.used)} / ${bytes(s.budget.limit)} · 被阻止 ${s.budget.blocked} 次`;$('progress').max=s.budget.limit;$('progress').value=s.budget.used;$('traffic').textContent=`Host 累计正文：接收 ${bytes(s.traffic.rx_body)} / 发送 ${bytes(s.traffic.tx_body)}。当前页面 API：接收 ${bytes(stats.rx)} / 发送 ${bytes(stats.tx)}（不含初始页面和请求头）。`;}
async function windows(){const r=await api('windows');const select=$('window');select.replaceChildren(new Option('选择 Mac 上已经打开的窗口',''));for(const w of r.windows)select.add(new Option(`${w.app} · ${w.title||'无标题'} [${w.id}]`,w.id));if(lastStatus.window)select.value=String(lastStatus.window.id);}
async function connect(){await status();$('pair').hidden=true;await windows();note(location.protocol==='https:'?'已连接。默认手动更新；先选窗口，再读取文字或画面。':'当前是 HTTP。仅用于本机、可信 Wi-Fi 或已加密私网；不要把此端口暴露到公网。');}
async function frame(){const raw=await api('frame',{base:revision,width:Number($('width').value),quality:Number($('quality').value),roi:$('roi').value.split(',').map(Number)});const view=new DataView(raw);if(raw.byteLength<4)throw new Error('无效画面包');const len=view.getUint32(0);if(len>raw.byteLength-4)throw new Error('无效画面头');const h=JSON.parse(new TextDecoder().decode(raw.slice(4,4+len)));if(!h.full&&h.base!==revision){revision='';throw new Error('画面基线不一致，请重新刷新');}const canvas=$('canvas');if(h.full){canvas.width=h.width;canvas.height=h.height;}const ctx=canvas.getContext('2d');let offset=4+len;try{for(const tile of h.tiles){if(offset+tile.bytes>raw.byteLength)throw new Error('画面块不完整');const blob=new Blob([raw.slice(offset,offset+tile.bytes)],{type:'image/jpeg'});offset+=tile.bytes;const url=URL.createObjectURL(blob);try{const image=new Image();image.src=url;await image.decode();ctx.drawImage(image,tile.x,tile.y);}finally{URL.revokeObjectURL(url);}}if(offset!==raw.byteLength)throw new Error('多余画面数据');revision=h.revision;}catch(e){revision='';throw e;}canvas.style.display='block';$('empty').hidden=true;$('frameInfo').textContent=`${h.full?'完整基线':'局部增量'} · ${h.tiles.length} 块 · 本次 ${bytes(raw.byteLength)} · ${new Date().toLocaleTimeString()}`;stats.frames++;await status();}
async function action(data){await api('action',{...data,request_id:randomID()});stats.actions++;note('Host 已接受操作。没有自动重试；请核对结果。');}
async function visual(data){if(!revision)throw new Error('请先刷新画面');await action({mode:'visual',revision,...data});await frame();}
async function semantics(){const result=await api('semantics');semanticRevision=result.revision;const wrap=$('nodes');wrap.replaceChildren();$('warnings').textContent=result.warnings.join(' ');for(const node of result.nodes){const row=document.createElement('div');row.className='node';const role=document.createElement('div');role.className='role';role.textContent=node.role;row.append(role);const label=document.createElement('strong');label.textContent=node.label;row.append(label);if(node.editable){const input=document.createElement('textarea');input.value=node.value;input.disabled=!node.enabled;const save=document.createElement('button');save.textContent='写入原控件（替换全文，不提交）';save.disabled=!node.enabled;save.onclick=()=>run(async()=>{await action({mode:'semantic',action:'set',node:node.id,revision:semanticRevision,text:input.value});revision='';await semantics();});row.append(input,save);}else if(node.value){const val=document.createElement('pre');val.textContent=node.value;row.append(val);}if(node.pressable){const button=document.createElement('button');button.textContent='操作此控件';button.disabled=!node.enabled;button.onclick=()=>run(async()=>{if(!confirm(`在 Mac 真实操作：${node.label||node.role}？`))return;await action({mode:'semantic',action:'press',node:node.id,revision:semanticRevision});revision='';await semantics();});row.append(button);}wrap.append(row);}filterNodes();await status();}
function filterNodes(){const q=$('filter').value.toLowerCase();for(const row of $('nodes').children)row.hidden=!row.textContent.toLowerCase().includes(q)&&![...row.querySelectorAll('textarea')].some(x=>x.value.toLowerCase().includes(q));}
function stopAuto(){clearTimeout(timer);timer=null;$('auto').checked=false;}
function schedule(){clearTimeout(timer);if($('auto').checked&&!document.hidden)timer=setTimeout(async()=>{if(!busy)await run(frame);if($('auto').checked)schedule();},3000);}
$('connect').onclick=()=>run(async()=>{token=$('token').value.trim()||token;try{sessionStorage.setItem('wc-token',token);}catch{}$('token').value='';await connect();});
$('windows').onclick=()=>run(windows);$('status').onclick=()=>run(status);$('semantics').onclick=()=>run(semantics);$('frame').onclick=()=>run(frame);
$('window').onchange=()=>run(async()=>{resetView();if(!$('window').value)return;await api('select',{window:Number($('window').value)});await status();note('已选择真实窗口。切换呈现方式不会启动第二份应用。');});
$('claim').onclick=()=>run(async()=>{await api('claim');await status();note('已取得控制权。文字写入、点击和快捷键会作用于你的 Mac。');});$('release').onclick=()=>run(async()=>{await api('release');await status();});
$('activate').onclick=()=>run(async()=>{await action({action:'activate'});revision='';await frame();});$('filter').oninput=filterNodes;
$('canvas').onclick=e=>{if(!$('clickMode').checked)return;const r=e.target.getBoundingClientRect();run(()=>visual({action:'click',x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}));};
$('send').onclick=()=>run(async()=>{const text=$('text').value;if(!text)return;await visual({action:'text',text});$('text').value='';});
for(const b of document.querySelectorAll('[data-key]'))b.onclick=()=>run(()=>visual({action:'key',key:b.dataset.key}));
for(const b of document.querySelectorAll('[data-scroll]'))b.onclick=()=>run(()=>visual({action:'scroll',delta:Number(b.dataset.scroll)}));
$('auto').onchange=()=>{if($('auto').checked){note('已主动开启 3 秒刷新；预算耗尽、出错或页面隐藏时停止。');schedule();}else stopAuto();};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAuto();});
for(const id of ['width','quality','roi'])$(id).onchange=()=>{revision='';note('参数已更改。下一次刷新需要新基线；不会自动发送画面。');};
$('export').onclick=()=>{const report={version:'0.1.0-demo',time:new Date().toISOString(),client:stats,host:{version:lastStatus.version,permissions:lastStatus.permissions,budget:lastStatus.budget,traffic:lastStatus.traffic},scope:'No token, window title, text, screenshot, IP or user-agent. HTTP bodies, not carrier bytes.'};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='continuity-diagnostic.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('disconnect').onclick=()=>run(async()=>{stopAuto();try{await api('release');}catch{}token='';try{sessionStorage.removeItem('wc-token');sessionStorage.removeItem('wc-client');}catch{}resetView();$('pair').hidden=false;$('linkState').textContent='已断开';note('仅断开访问端；Mac 的应用和任务继续运行。');});
if(token)run(connect);
